[general]
RemoteNickFormat="{NICK} : "
PreserveThreading=true
# Show messages announcing when people arrive/leave remote channels

#[slack.example]
##Token to connect with the Slack API
##You'll have to use a test/api-token using a dedicated user and not a bot token.
##See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
#Token="${SLACK_EXAMPLE_TOKEN}" # real user

[slack]
[slack.pim]
Token="${SLACK_TOKEN}"
PrefixMessagesWithNick=true

[discord]
[discord.pim]
Token="${DISCORD_TOKEN}"
Server="${DISCORD_SERVER_NAME}"

[[gateway]]
name = "mygateway"
enable=true

    [[gateway.inout]]
    account = "discord.pim"
    channel="${DISCORD_CH1}"

    [[gateway.inout]]
    account ="slack.pim"
    channel = "${SLACK_CH1}"
